baseurl: "/Portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext
  - scope:
      path: "assets/images/portfolio/HomeTown"
    values:
      HomeTown: true
  - scope:
      path: "assets/images/portfolio/ConsoleGraphics"
    values:
      ConsoleGraphics: true
  - scope:
      path: "assets/images/portfolio/Screensavers"
    values:
      Screensavers: true
  - scope:
      path: "assets/images/portfolio/TheHuntForZelandia"
    values:
      TheHuntForZelandia: true
collections:
  projects:
    output: true


include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
